#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-django_compressor
Version  : 4.0
Release  : 60
URL      : https://files.pythonhosted.org/packages/f1/c4/0e90d34014a5027365f6448067b84a3bb7558ed7daa0d7fd72a3708e2922/django_compressor-4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f1/c4/0e90d34014a5027365f6448067b84a3bb7558ed7daa0d7fd72a3708e2922/django_compressor-4.0.tar.gz
Summary  : Compresses linked and inline JavaScript or CSS into single cached files.
Group    : Development/Tools
License  : MIT
Requires: pypi-django_compressor-python = %{version}-%{release}
Requires: pypi-django_compressor-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(django_appconf)
BuildRequires : pypi(py)
BuildRequires : pypi(rcssmin)
BuildRequires : pypi(rjsmin)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
Django Compressor
=================
.. image:: https://codecov.io/github/django-compressor/django-compressor/coverage.svg?branch=develop
:target: https://codecov.io/github/django-compressor/django-compressor?branch=develop

%package python
Summary: python components for the pypi-django_compressor package.
Group: Default
Requires: pypi-django_compressor-python3 = %{version}-%{release}

%description python
python components for the pypi-django_compressor package.


%package python3
Summary: python3 components for the pypi-django_compressor package.
Group: Default
Requires: python3-core
Provides: pypi(django_compressor)
Requires: pypi(django_appconf)
Requires: pypi(rcssmin)
Requires: pypi(rjsmin)

%description python3
python3 components for the pypi-django_compressor package.


%prep
%setup -q -n django_compressor-4.0
cd %{_builddir}/django_compressor-4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650737466
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . rjsmin
pypi-dep-fix.py . rcssmin
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
pypi-dep-fix.py %{buildroot} rjsmin
pypi-dep-fix.py %{buildroot} rcssmin
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
